In [3]:
print('Hi Shyam (my world)')

Hi Shyam (my world)


In [6]:
if (5 > 4):
    print('lezgo')
else:
    print('aw man')

lezgo


In [9]:
list1 = ['hi', 'hello']
for i in list1:
    print(i)
print(list1)
print(len(list1))

hi
hello
['hi', 'hello']
2


In [10]:
tuple1 = ('Apple','Bananas','Shyam')
x,y,z = tuple1
print(x,y,z)

Apple Bananas Shyam


In [14]:
dict1 = {'A': 1, 'B': 2, 'C': 3, 'D': ['i','k']}
print(dict1)

{'A': 1, 'B': 2, 'C': 3, 'D': ['i', 'k']}


In [16]:
dict1['D']

['i', 'k']

In [17]:
dict1.update({'D': ['i','c']})

In [22]:
for i in dict1.items():
    print(i)
for i in dict1.keys():
    print(i)

('A', 1)
('B', 2)
('C', 3)
('D', ['i', 'c'])
A
B
C
D


In [31]:
arr1 = [1,2,5,7,9]
for i in arr1:
    print(i)
print(arr1[2])
print(len(arr1))
arr1.append(4)
len(arr1)
print(arr1)
arr1.pop(1)
print(arr1)

1
2
5
7
9
5
5
[1, 2, 5, 7, 9, 4]
[1, 5, 7, 9, 4]


In [32]:
import numpy as np

In [33]:
!pip install numpy

In [34]:
import numpy as np

In [52]:
arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))
for i in arr1:
    print(i)
print(arr1.ndim)
arr2 = np.array([[1,2,3,11,22,33],[4,5,6,44,55,66],[7,8,9,77,88,99]])
print(arr2.ndim)
print(arr2)
print(arr2[:2,3:]) #0th to 1st row and 3rd to 5th column
print(arr2[::-1,::-1])

[1 2 3]
<class 'numpy.ndarray'>
1
2
3
1
2
[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]
 [ 7  8  9 77 88 99]]
[[11 22 33]
 [44 55 66]]
[[99 88 77  9  8  7]
 [66 55 44  6  5  4]
 [33 22 11  3  2  1]]


In [53]:
import pandas as pd

In [67]:
arr1 = [1,2,3,4]
arri = ['one','two','three','four']
d1 = pd.Series(arr1, index = arri)
print(d1)
dict1 = {'data': ['one','two','three'], 'rains': ['yes','no','NaN']}
d2 = pd.DataFrame(dict1, index = [1,2,3])
d2

one      1
two      2
three    3
four     4
dtype: int64


data rains
1    one   yes
2    two    no
3  three   NaN